server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    hikari:
      username: root
      password: '2083298840'
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


  security:
    user:
      name: admin
      password: 123